App\Models\Employee:
  attributes:
    firstName:
      field_name: 'first_name'
      rules: ['required']
      skip_on_rule_fail: true
    lastName:
      field_name: 'last_name'
      rules: ['required']
      skip_on_rule_fail: true

